requirements.txt
setup.cfg
setup.py

Searching around for a solution to my versioning woes, I found this library. It reads the version from the git tag. With my other PR that will add a publish to pypi on commit, we just need to push to master and add the version tag to publish.

Use pbr library for versioning

---

README.md
json_schema_for_humans/generate.py
json_schema_for_humans/schema_doc.css
json_schema_for_humans/templates/schema_doc.template.html
tests/cases/top_level_array.json
tests/cases/top_level_combining.json
tests/generate_test.py

- Add optional expand all and collapse all buttons (#11)
- Fix bottom border missing on last card
- Fix schema with other types than object at the top level not being rendered (#12)
- Don't crash with SameFileError copying the CSS file
- Run black

Add optional expand all and collapse all buttons

---

json_schema_for_humans/templates/schema_doc.template.html

Fix reference resolution broken on schemas with top level not an object

---

docs/_data/examples.yaml
json_schema_for_humans/generate.py
json_schema_for_humans/schema_doc.css
json_schema_for_humans/templates/schema_doc.template.html
tests/cases/pattern_properties.json
tests/generate_test.py

- Use badge-info for pattern property badge
- Add test for feature
- Update yaml file for documentation
- Add new method for generating id, since current escape mechanism is
inappropriate
- Add named_property flag to templates to control whether the title of
the element or the actual property name is rendered

#24: Implement pattern property rendering

---

README.md
json_schema_for_humans/generate.py
json_schema_for_humans/templates/schema_doc.template.html
tests/cases/conditional_subschema.json
tests/cases/conditional_subschema_no_else.json
tests/generate_test.py

Closes #27 
Also sneaking in some other changes

[WIP] Support for conditional subschema

---

json_schema_for_humans/templates/schema_doc.template.html
tests/cases/html_in_patterns.json
tests/generate_test.py

Escape HTML in property names and regular expressions

---

README.md
json_schema_for_humans/generate.py
requirements.txt
tests/cases/yaml.yaml
tests/generate_test.py

Support YAML for schema files

---

json_schema_for_humans/templates/section_description.html

Fix HTML Ids for "Read More" and "Read Less" buttons

---

json_schema_for_humans/templates/content.html
tests/cases/single_element_allOf.json
tests/generate_test.py

Was seeing this for one of my schemas - seems like a typo when refactoring.  Added a unit test to expose the issue

Fixing UndefinedError caused by schemas with single-element allOf/anyOf

---

docs/_data/examples.yaml
docs/_includes/examples/additional_properties.json
json_schema_for_humans/generate.py
json_schema_for_humans/schema_doc.css
json_schema_for_humans/templates/content.html
json_schema_for_humans/templates/section_properties.html
tests/cases/additional_properties.json
tests/generate_test.py

Opening as a draft to ask some questions.

Add support for additionalProperties

---

setup.py

Install templates on setup

---

json_schema_for_humans/templates/flat/section_description.html
json_schema_for_humans/templates/js/section_description.html

Place Read More in a block element

---

docs/examples/examples_md_default/defaults.md
docs/examples/examples_md_default/description_from_ref.md
docs/examples/examples_md_default/description_with_ref.md
docs/examples/examples_md_default/recursive.md
docs/examples/examples_md_default/recursive_array.md
docs/examples/examples_md_default/recursive_parent_in_definition.md
docs/examples/examples_md_default/recursive_two_files.md
docs/examples/examples_md_default/references.md
docs/examples/examples_md_default/references_url_two_levels.md
docs/examples/examples_md_default/with_definitions.md
docs/examples/examples_md_default/with_descriptions.md
docs/examples/examples_md_with_badges/defaults.md
docs/examples/examples_md_with_badges/description_from_ref.md
docs/examples/examples_md_with_badges/description_with_ref.md
docs/examples/examples_md_with_badges/recursive.md
docs/examples/examples_md_with_badges/recursive_array.md
docs/examples/examples_md_with_badges/recursive_parent_in_definition.md
docs/examples/examples_md_with_badges/recursive_two_files.md
docs/examples/examples_md_with_badges/references.md
docs/examples/examples_md_with_badges/references_url_two_levels.md
docs/examples/examples_md_with_badges/with_definitions.md
docs/examples/examples_md_with_badges/with_descriptions.md
json_schema_for_humans/md_template.py

New branch for PR #84.  Fixes issue #85

Link shouldn't be code

---

pyproject.toml

Made a quick fix.
Resolves #133.

Include schema in package

---

docs/Examples.md
docs/examples/cases/empty_property_name.json
docs/examples/examples_flat_default/empty_property_name.html
docs/examples/examples_js_default/empty_property_name.html
docs/examples/examples_md_default/empty_property_name.md
docs/examples/examples_md_nested_default/empty_property_name.md
docs/examples/examples_md_nested_with_badges/empty_property_name.md
docs/examples/examples_md_with_badges/empty_property_name.md
json_schema_for_humans/jinja_filters.py
tests/generate_test.py

Don't crash on empty property names

---

poetry.lock
pyproject.toml

See issue https://github.com/coveooss/json-schema-for-humans/issues/157

added MarkUpSafe as an explicit dependency

---

docs/Examples.md
docs/examples/cases/broken_ref.json
docs/examples/examples_flat_default/broken_ref.html
docs/examples/examples_js_default/broken_ref.html
docs/examples/examples_md_default/broken_ref.md
docs/examples/examples_md_nested_default/broken_ref.md
docs/examples/examples_md_nested_with_badges/broken_ref.md
docs/examples/examples_md_with_badges/broken_ref.md
json_schema_for_humans/schema/intermediate_representation.py
json_schema_for_humans/schema/schema_node.py
pyproject.toml
tests/generate_test.py

- Generate error message in doc for missing schema reference instead of crashing
- Display description when next to a $ref

Generate error message in doc for missing schema reference

---

docs/Examples.md
docs/examples/cases/type_object_null.json
docs/examples/examples_flat_default/type_object_null.html
docs/examples/examples_js_default/schema_doc.css
docs/examples/examples_js_default/type_object_null.html
docs/examples/examples_js_offline_default/type_object_null.html
docs/examples/examples_md_default/type_object_null.md
docs/examples/examples_md_nested_default/type_object_null.md
docs/examples/examples_md_nested_with_badges/type_object_null.md
docs/examples/examples_md_with_badges/type_object_null.md
json_schema_for_humans/schema/schema_keyword.py
json_schema_for_humans/schema/schema_node.py
json_schema_for_humans/templates/md/content.md
json_schema_for_humans/templates/md_nested/content.md

Fix properties missing in MD template when type is object and others

---

json_schema_for_humans/jinja_filters.py
json_schema_for_humans/schema/schema_keyword.py
json_schema_for_humans/schema/schema_node.py
json_schema_for_humans/template_renderer.py
json_schema_for_humans/templates/flat/content.html
json_schema_for_humans/templates/js/content.html
json_schema_for_humans/templates/js_offline/content.html

This pull request implements support for `meta:enum` as described in #227.

Added initial support for meta:enum

---

poetry.lock
pyproject.toml

This was moved to the wrong place in #241

Move types packages to dev-dependencies

---

config_schema.json

I noticed I got an error stemming from this while trying to regenerate examples.
@dblanchette

Remove trailing comma in config_schema.json

---

docs/examples/cases/complex_const.json
docs/examples/examples_flat_default/complex_const.html
docs/examples/examples_js_default/complex_const.html
docs/examples/examples_js_offline_default/complex_const.html
docs/examples/examples_md_default/complex_const.md
docs/examples/examples_md_nested_default/complex_const.md
docs/examples/examples_md_nested_with_badges/complex_const.md
docs/examples/examples_md_with_badges/complex_const.md
json_schema_for_humans/jinja_filters.py
json_schema_for_humans/schema/intermediate_representation.py
json_schema_for_humans/schema/schema_node.py
json_schema_for_humans/templates/flat/content.html
json_schema_for_humans/templates/js/content.html
json_schema_for_humans/templates/js_offline/content.html
json_schema_for_humans/templates/md/content.md
json_schema_for_humans/templates/md/section_conditional_subschema.md
json_schema_for_humans/templates/md_nested/content.md
json_schema_for_humans/templates/md_nested/section_conditional_subschema.md
json_schema_for_humans/templating_utils.py
tests/generate_test.py

With:
```json
{
"const": "null"
}
```
we would get

fix: const with value null wrongly displayed
