- json_schema_for_humans/templates/schema_doc.template.html
Fixing two template issues that I noticed:
1. Missing "Required" tag on nested objects due to scope of `required_properties`.
The initial `set required_properties = ...` works because the code is in the global scope but the set statement for nested objects is missed because it's limited to that function call's scope.
2. Processing of nested objects corrupts parent object since the same variable name is used.
This code `for property_name, property in property["properties"].items()` is problematic because at the end of the for loop, `property` will be set to the last sub-property.  This causes problems for the code after that `for` loop that are using `property`, expecting it to be the parent (not the last sub-property)
> Fixing two template issues

- json_schema_for_humans/generate.py
- tests/generate_test.py
I think it's easier to work with paths as strings instead of list and let Python built-in functions deal with relative paths.
I also restructured the `resolve_ref` function to make it easier to read (for me at least)
@sw23 Since you worked on this, any thoughts?
> Refactor generate_from_schema to accept schema_path as a string

- json_schema_for_humans/templates/schema_doc.template.html
- tests/generate_test.py
The `description` node at the root of the schema was being ignored.
> Add top level description

- json_schema_for_humans/generate.py
- tests/cases/description_with_ref.json
- tests/generate_test.py
- tox.ini
There is 2 ways we might want to add a description when using a reference.
Let's take this example:
```json
{
"type": "object",
"properties": {
"outer": {
"$ref": "#/definitions/inner schema"
}
},
"$id": "my-id",
"$schema": "http://json-schema.org/draft-07/schema#",
"definitions": {
"inner schema": {
"type": "object",
"properties": {
"inner": {
"type": "string"
}
}
}
}
}
```
If we want to see a description under `outer`, we could do:
```json
{
"type": "object",
"properties": {
"outer": {
"$ref": "#/definitions/inner schema",
"description": "A description"
}
},
"$id": "my-id",
"$schema": "http://json-schema.org/draft-07/schema#",
"definitions": {
"inner schema": {
"type": "object",
"properties": {
"inner": {
"type": "string"
}
}
}
}
}
```
(Not a valid JSON schema in older drafts, but valid …
> Use description when it is next to a $ref

- json_schema_for_humans/generate.py
- json_schema_for_humans/schema_doc.css
- json_schema_for_humans/templates/schema_doc.template.html
- requirements.txt
- tests/cases/with_examples.json
- tests/generate_test.py
Dear maintainers,
first of all I would like to thank you for this wonderful Python library. For a current research project we need the presentation of JSON-examples in the HTML-documentation of our JSON-schemas. I have made the necessary changes to a local version of this library and would like to share them with you.
The 2 changes made are:
1. representation of the property "examples" (not supported so far):
2. decoding unicode-escapes in the generated result
I'm looking forward to your review.
Kind regards
> Add support for JSON-Schema "examples"-property, UTF-8 compatibility in generated result

- json_schema_for_humans/generate.py
- tests/cases/pattern_properties_html_id.json
- tests/generate_test.py
Fixes #41 
HTML IDs for patterns under "patternProperties" will now use their index under their current schema node. This ensures there can be no duplicate which could be the case when using the pattern itself with special chars replaced by underscore.
> Ensure HTML IDs for patternProperties are unique

- json_schema_for_humans/generate.py
- tests/generate_test.py
Closes #45
Per discussion on issue, if the schema extension is ".json" load the schema with json.load, otherwise try with yaml.safe_load. Adds a regression test.
> Parse json files using json rather than yaml

- tox.ini
Not sure why but tox doesn't work for me (Powershell, Windows 10) unless I add pyyaml.  Adding as a proposal here, unless it's supposed to be picked up some other way?
Tox fails with this:
```
_____________________________________________________________________________ ERROR collecting tests/generate_test.py _____________________________________________________________________________ 
ImportError while importing test module '...\tests\generate_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\generate_test.py:8: in <module>
from json_schema_for_humans.generate import generate_from_file_object, generate_from_schema
json_schema_for_humans\generate.py:17: in <module>
import yaml
E   ModuleNotFoundError: No module named 'yaml' 
```
> pyyaml needed by tox to test correctly?

- json_schema_for_humans/generate.py
Tabs get a default title unless `anyOf`/`oneOf`/`allOf`s reference another schema at the moment. In the case they don't reference another schema, check for a `title` field and use that as the tab title if available.
**Before**
**After**
> Use title for definition name where ref file name isn't available

- json_schema_for_humans/templates/js/section_properties.html
Please refer https://getbootstrap.com/docs/4.4/utilities/spacing/#notation for the change.
> Increased the left padding of section properties to make the doc more readable

- json_schema_for_humans/generate.py
The uncollapsing of properties with a comma (e.g. "0,0") was not working because the comma was not being escaped (same as issue #70 had with points). Escaping them fixes the issue.
> Fix issue with unescaped commas

- config_schema.json
- json_schema_for_humans/generate.py
Changes:
* Move global `TEMPLATE_FOLDER` var onto configuration object as `template_folder`, default of `templates`
* Create `template_base` configuration option for the base path name, with default of the module's path
* Update documentation of config options to describe these, and standardize trailing punctuation
Closes #78
> Allow filepath to templates to be configured

- json_schema_for_humans/templates/flat/base.html
- json_schema_for_humans/templates/js/base.html
The `<footer>` element must not be placed outside of `<body>`.
According to the [MDN docs on the `html` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html),
> Permitted content: One <head> element, followed by one <body> element.
I triggered regeneration of the examples (which also contain the wrong HTML) locally, but that resulted in additional unrelated changes, so I didn't commit any changes to the examples.
> Fix invalid HTML as `<footer>` must not be sibling of `<body>`

- json_schema_for_humans/jinja_filters.py
Fixes deprecation warning in jinja.
```
DeprecationWarning: 'environmentfilter' is renamed to 'pass_environment', the old name will be removed in Jinja 3.1.
```
> Update import per jinja deprecation warning

- json_schema_for_humans/generate.py
- tests/cli_test.py
- tests/interface_test.py
- tests/test_utils.py
Closes #97 
- Throw FileNotFoundError if output directory is invalid
- Catch and rethrow as ClickException in main()
- Add tests for cli and for specific functions
> Throw appropriate and informative error if the output dir is missing

- json_schema_for_humans/generation_configuration.py
- json_schema_for_humans/jinja_filters.py
- json_schema_for_humans/template_renderer.py
- json_schema_for_humans/templates/md/section_examples.md
This PR aims to fix the `md` template when `examples_as_yaml` is enabled.
In the current situation, this would render HTML, which is not compatible with (for example) the GitHub Markdown renderer.
This PR would render the yaml as-is.
It also fixes an issue where the file extension for custom templates would be returned as `.md` instead of `md`.
> fix: Fix yaml example in md template

- docs/Examples.md
- docs/examples/cases/with_urlencoded_anchor.json
- docs/examples/examples_flat_default/with_urlencoded_anchor.html
- docs/examples/examples_js_default/with_urlencoded_anchor.html
- docs/examples/examples_md_default/with_urlencoded_anchor.md
- docs/examples/examples_md_nested_default/with_urlencoded_anchor.md
- docs/examples/examples_md_nested_with_badges/with_urlencoded_anchor.md
- docs/examples/examples_md_with_badges/with_urlencoded_anchor.md
- json_schema_for_humans/schema/intermediate_representation.py
- tests/generate_test.py
In version 0.39.5 trying to rener a schema like
https://json.schemastore.org/dss-2.0.0.json or
https://json.schemastore.org/opspec-io-0.1.7.json
throws a KeyError e.g: `KeyError: 'dss2-SigningTimeInfoType%3ASigningTimeBoundaries'`
because the anchor ref is URL Encoded but the JSON keys aren't.
This PR fixes the issue and I've added an example/test case based on stripping down https://json.schemastore.org/dss-2.0.0.json to a minimal case.
Hopefully I've followed all the contributing guidelines correctly :crossed_fingers:
> Handle urlencoded characters in anchor refs

- .github/workflows/pythonpackage.yml
- CONTRIBUTING.md
- pyproject.toml
- tox.ini
The build is broken on Python 3.6. This version is end of life, so let's remove it.
> Deprecate py36

- json_schema_for_humans/jinja_filters.py
- tests/generate_test.py
YAML examples will have the keys in objects sorted, which differs to the behavior of the JSON examples. Adding `sort_keys=False` makes the YAML examples match the JSON examples.
<table>
<tr>
<th>Source</th>
<th>JSON</th>
<th>YAML Before</th>
<th>YAML After</th>
</tr>
<tr>
<td>
```json
"examples": [
{
"z": 1,
"y": 2,
"x": 3
}
]
```
</td>
<td>
```json
{
"z": 1,
"y": 2,
"x": 3
}
```
</td>
<td>
```yaml
x: 3,
y: 2,
z: 1
```
</td>
<td>
```yaml
z: 1
y: 2
x: 3
```
</td>
</tr>
</table>
</table>
</table>
> Do not sort YAML keys in examples

- json_schema_for_humans/jinja_filters.py
- tests/generate_test.py
> Fix Spurious ellipsis in YAML examples

- json_schema_for_humans/md_template.py
In md_template.properties_table, we call:
escape_for_table(sub_property.property_name)
`sub_property` is a `SchemaNode`, making `property_name` an
`Optional[str]`.
`escape_for_table` expected `str` as input. Adjust it to accept
`Optional[str]`.
> Fix a typing error

- json_schema_for_humans/templates/md/breadcrumbs.md
Previously array item headings would show as "None" when breadcrumbs
were disabled. Now they show the correct trailing value "<array> items".
Example:
```diff
-  - [7.1. None](#autogenerated_heading_2)
+  - [7.1. rds items](#autogenerated_heading_2)
```
> fix(md): Correct non-breadcrumb array item headings

- json_schema_for_humans/templates/md/breadcrumbs.md
We were generating headings like:
```md
- [1. Property `version<br />`](#version)
```
Due to a spurious newline getting introduced in `breadcrumbs.md` when `config.show_breadcrumbs` was `False`.
It was added by line 7 specifically, eg the middle line here:
```jinja
{%- else -%}
{{ schema.name_for_breadcrumbs }}
{% endif %}
```
And could be fixed by adding `-` to the start of the `endif` directive in above snippet only.
But for safety / consistency, add whitespace trimming to almost all directives in this template.
> Fix <br /> in headings without breadcrumbs

- json_schema_for_humans/schema/intermediate_representation.py
Fixes issue where HTML property does not expand when the property name contains the `$`  character.
> Add dollar sign to forbidden chars.

- README.md
- docs/examples/cases/references.json
- json_schema_for_humans/schema/intermediate_representation.py
The current implementation seems to support the format `file:./references.json`.
But looking at the [json schema specification](https://json-schema.org/draft/2020-12/json-schema-core.html#name-base-uri-anchors-and-derefe), it says that the $ref format follows RFC3986.
RFC 3986 says: (https://datatracker.ietf.org/doc/html/rfc3986#section-3)
```
URI = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
hier-part = "//" authority path-abempty
/path-absolute
/path-rootless
/path-empty
```
In other words, shouldn't the format starting with "file:" be `file://./references.json` instead of `file:./references.json`?
As for the test, `file_prefix` was the same as `a_gift`, so I changed this.
https://github.com/coveooss/json-schema-for-humans/blob/6a467492d697c4a44a409409ab0391a4a4acd291/docs/exampl …
> Fix test for $ref file schema 

- json_schema_for_humans/jinja_filters.py
E.g. if the description contains `<html>` tags this leads to issues.
`markupsafe.escape()` was the first HTML escaper to pop up, so I went with that.
> jinja_filters.py: Add escaping for unsafe input.

- json_schema_for_humans/templating_utils.py
set is not ordered and may lead to not reproducible results between different python implementation. The root cause probably lays in different hash function implementation. 
Windows Python 3.10.11:
```
>>> set((type(None),str)) 
{<class 'NoneType'>, <class 'str'>}
```
Ubuntu Python 3.10.11
```
>>> set((type(None), str))
{<class 'str'>, <class 'NoneType'>}
```
> Fix for unstable enum description templating_utils.py

- json_schema_for_humans/schema/schema_keyword.py
- json_schema_for_humans/schema/schema_node.py
- json_schema_for_humans/templates/js/section_properties.html
- json_schema_for_humans/templates/js_offline/section_properties.html
Hello,
I was trying to mark a property for a project I am working on as deprecated but couldn't get the badge to show up. Using a newer version of JSON Schema the `deprecated` field has been added but wasn't supported here.
I've added a `@property` called `kw_deprecated` so it can be used to check if the property exists or not. I have also updated the Javascript templates to support with the correct tagging now.
> Support for Deprecated Keyword

- tests/generate_test.py
Small PR - resolve the `bs4` deprecation warnings which you can see in the [CI logs](https://github.com/coveooss/json-schema-for-humans/actions/runs/14600985691/job/40958798367#step:9:87):
```python
/home/runner/work/json-schema-for-humans/json-schema-for-humans/tests/generate_test.py:418: DeprecationWarning: Call to deprecated method findChildren. (Replaced by find_all) -- Deprecated since version 3.0.0.
examples_content_text = [ex.findChildren()[0].text for ex in examples_content]
```
> Resolve bs4 deprecation warnings
